config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
get 'username', to: 'pages#username', as: 'username'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#index'


  get 'z0faas', to: 'pages#z0faas', as: 'z0faas'

  get 'shalin', to: 'pages#shalin', as: 'shalin'

  get 'alissamartini', to: 'pages#alissamartini', as: 'alissamartini'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end


  def z0faas
  end
  def shalin
    render :shalin
  end
  def alissamartini
  end
end

def username
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/AlissaMartini.html.erb
<h1> This is Alissa's Page </h1>
<body>
 <ul>
        <li>I like Fruit</li>
        <li>I'm Hispanic </li>
        <li>I speak 3 languages..sorta </li>
 </ul>


</body>

app/views/pages/Justin-Martin1.html.erb
"Justin Martin, 23, Computer Science, Senior"

app/views/pages/Shalin_Maria.html.erb
<!DOCTYPE html>
<section>
    <p>My name is Shalin Maria and I am a senior at the University of Memphis taking the 3081-Introduction to Software Engineering class.</p>
</section>

app/views/pages/alissamartini.html.erb
<h1> This is Alissa's Page </h1>
<body>
 <ul>
        <li>I like Fruit</li>
        <li>I'm Hispanic </li>
        <li>I speak 3 languages..sorta </li>
 </ul>


</body>

app/views/pages/index.html.erb
<h1>Directory of Student Pages</h1>

<ul>

    <li><%= link_to 'justin-martin1', justin-martin1_path %></li>


    <li><%= link_to 'z0faas', z0faas_path %></li>


    <li><%= link_to 'shalin', shalin_path %></li>

    <li><%= link_to 'alissamartini', alissamartini_path %></li>



</ul>

app/views/pages/shalin.html.erb
<!DOCTYPE html>
<section>
    <p>My name is Shalin Maria and I am a senior at the University of Memphis taking the 3081-Introduction to Software Engineering class.</p>
</section>

app/views/pages/z0faas.html.erb
<h1>My name is Jonathan Maronde</h1>

<p>CS3 is a fun class</p>